# tradable_forex.py - Cập nhật: 2025-11-06 13:10
TRADABLE_FOREX = [
    "EURUSD",
    "GBPUSD",
    "USDCHF",
    "USDJPY",
    "USDCAD",
    "AUDUSD",
    "EURGBP",
    "EURJPY",
    "NZDUSD",
    "AUDCAD",
    "AUDCHF",
    "EURCHF",
    "NZDCAD",
    "NZDCHF",
    "NZDJPY",
    "AUDNZD",
    "AUDJPY",
    "EURAUD",
    "EURCAD",
    "GBPCHF",
    "GBPAUD",
    "GBPCAD",
    "EURNZD",
    "GBPJPY",
    "GBPNZD",
]
